"""Execution-aware research simulation utilities."""

from chronoslob.backtest.costs import (
    CostBreakdown,
    ExecutionCostConfig,
    FeeModel,
    SpreadCostModel,
    estimate_aggressive_cost,
    estimate_passive_cost,
    estimate_total_cost,
)
from chronoslob.backtest.execution import (
    ExecutionDecision,
    ExecutionFill,
    ExecutionMode,
    ExecutionResult,
    MarketState,
    PredictionSignal,
    TradeSide,
    side_sign,
)
from chronoslob.backtest.latency import (
    DEFAULT_LATENCY_GRID,
    LatencyConfig,
    LatencyResult,
    apply_latency,
    get_latency_state,
    latency_sensitivity_grid,
)
from chronoslob.backtest.risk import (
    RiskCheck,
    RiskConfig,
    RiskState,
    apply_drawdown_limit,
    apply_inventory_limit,
    apply_turnover_limit,
    should_abstain_for_risk,
    update_risk_state,
)
from chronoslob.backtest.turnover import (
    TurnoverSummary,
    compute_average_holding_period,
    compute_position_path,
    compute_trade_count,
    compute_turnover,
)
from chronoslob.backtest.validation import (
    ExecutionValidationConfig,
    ExecutionValidationResult,
    ExecutionValidationSummary,
    confidence_threshold_sweep,
    latency_sensitivity_analysis,
    run_execution_validation,
    run_execution_validation_smoke,
    summarise_execution_results,
)

__all__ = [
    "DEFAULT_LATENCY_GRID",
    "CostBreakdown",
    "ExecutionCostConfig",
    "ExecutionDecision",
    "ExecutionFill",
    "ExecutionMode",
    "ExecutionResult",
    "ExecutionValidationConfig",
    "ExecutionValidationResult",
    "ExecutionValidationSummary",
    "FeeModel",
    "LatencyConfig",
    "LatencyResult",
    "MarketState",
    "PredictionSignal",
    "RiskCheck",
    "RiskConfig",
    "RiskState",
    "SpreadCostModel",
    "TradeSide",
    "TurnoverSummary",
    "apply_drawdown_limit",
    "apply_inventory_limit",
    "apply_latency",
    "apply_turnover_limit",
    "compute_average_holding_period",
    "compute_position_path",
    "compute_trade_count",
    "compute_turnover",
    "confidence_threshold_sweep",
    "estimate_aggressive_cost",
    "estimate_passive_cost",
    "estimate_total_cost",
    "get_latency_state",
    "latency_sensitivity_analysis",
    "latency_sensitivity_grid",
    "run_execution_validation",
    "run_execution_validation_smoke",
    "should_abstain_for_risk",
    "side_sign",
    "summarise_execution_results",
    "update_risk_state",
]
